"""OnlyBots Verifier — main polling loop.

Polls the database for verification runs with status='running',
executes three sequential tests using CLI agent harnesses, and records results.

Usage:
    python main.py              # poll mode (runs forever)
    python main.py --once       # run once and exit (for manual/cron)
    python main.py --retry-failed  # re-queue failed services and run once
"""
from __future__ import annotations
import asyncio
import shutil
import sys
import time
import traceback
from datetime import datetime, timezone

from config import POLL_INTERVAL_SECONDS, VERIFIER_VERSION, HARNESSES
from db import (
    fetch_pending_runs, save_test_result, complete_run,
    update_service_status, retry_failed_services,
    queue_drift_check, find_drifted_services,
)
from evidence import get_evidence_dir
from tests.test_signup import TestSignup
from tests.test_persistence import TestPersistence
from tests.test_workflow import TestWorkflow


TESTS = [TestSignup(), TestPersistence(), TestWorkflow()]


async def verify_service(run: dict) -> None:
    """Run all three tests sequentially for a single service."""
    run_id = run["id"]
    service_id = run["service_id"]
    slug = run.get("slug", "")

    print(f"[verifier] Starting verification for {run['name']} (run {run_id})")

    # Gate: if there is no contract for this service, don't run tests. Mark the
    # run as 'awaiting_contract' and leave the service in its current state so
    # a submitter isn't permanently stuck at 'failed' while a contract is
    # being authored (or, later, generated by Phase 5 LLM pipeline).
    from contract import has_contract
    if slug and not has_contract(slug):
        print(f"[verifier] {run['name']}: NO CONTRACT — skipping verification, "
              f"marking run as awaiting_contract")
        complete_run(run_id, "awaiting_contract", None)
        # Do NOT touch service status — it stays whatever it was (pending, usually).
        return

    evidence_dir = get_evidence_dir(run_id)
    state: dict = {}  # shared state across tests (credentials, tokens, etc.)
    failed_at_step: int | None = None

    # Policy: run ALL three tests independently. Earlier failure no longer
    # short-circuits, because a failed signup doesn't invalidate the signal
    # that (say) persistence of an operator-provided key works, or that the
    # public API is alive. Tests whose `requires` depend on state a failed
    # upstream test was supposed to produce will fail themselves with a
    # clean "prerequisite unmet" reason — that's what they're designed to
    # do. The service's roll-up `failed_at_step` remains the FIRST failure
    # (signup autonomy dominates), matching the registry's semantics.
    for test in TESTS:
        print(f"  Running Test {test.test_number}: {test.test_name}...")

        try:
            result = await test.run(run, state, run_id)
        except Exception as e:
            traceback.print_exc()
            result = None

        if result is None:
            save_test_result(
                run_id=run_id,
                test_number=test.test_number,
                test_name=test.test_name,
                passed=False,
                confidence=0.0,
                failure_reason="Unhandled exception in test",
            )
            if failed_at_step is None:
                failed_at_step = test.test_number
            print(f"  Test {test.test_number}: EXCEPTION")
            continue

        save_test_result(
            run_id=run_id,
            test_number=test.test_number,
            test_name=test.test_name,
            passed=result.passed,
            confidence=result.confidence,
            failure_reason=result.failure_reason,
            evidence_artifacts=result.evidence_artifacts,
            details=result.details,
        )

        if result.passed:
            print(f"  Test {test.test_number}: PASS (confidence: {result.confidence:.0%})")
        else:
            print(f"  Test {test.test_number}: FAIL — {result.failure_reason}")
            if failed_at_step is None:
                failed_at_step = test.test_number

    if failed_at_step is None:
        verified_date = datetime.now(timezone.utc).isoformat()
        update_service_status(service_id, "verified", None, verified_date)
        complete_run(run_id, "passed", str(evidence_dir))
        print(f"[verifier] {run['name']}: VERIFIED ✓")
    else:
        # Drift signal: if the service was previously 'verified' and this run
        # failed, log a distinct line so ops can grep for regressions.
        was_verified = run.get("status_before_this_run") == "verified"
        # (status_before_this_run is the service's status at the moment we
        # fetched the run, before update_service_status flips it to 'failed')
        if was_verified:
            print(f"[verifier] {run['name']}: DRIFT DETECTED — "
                  f"previously verified, now failing at step {failed_at_step}")
        update_service_status(service_id, "failed", failed_at_step, None)
        complete_run(run_id, "failed", str(evidence_dir))
        print(f"[verifier] {run['name']}: FAILED at step {failed_at_step} ✗")


async def poll_once() -> int:
    runs = fetch_pending_runs()
    if not runs:
        return 0
    print(f"[verifier] Found {len(runs)} pending run(s)")
    for run in runs:
        await verify_service(run)
    return len(runs)


async def poll_loop() -> None:
    print(f"[verifier] OnlyBots Verifier v{VERIFIER_VERSION}")
    print(f"[verifier] Polling every {POLL_INTERVAL_SECONDS}s...")
    while True:
        try:
            count = await poll_once()
            if count > 0:
                print(f"[verifier] Processed {count} run(s)")
        except KeyboardInterrupt:
            print("\n[verifier] Shutting down...")
            break
        except Exception:
            traceback.print_exc()
            print("[verifier] Error in poll cycle, retrying...")
        time.sleep(POLL_INTERVAL_SECONDS)


def check_harnesses():
    """Check which CLI agent harnesses are installed."""
    print("[verifier] Checking installed harnesses:")
    for name, cfg in HARNESSES.items():
        cmd = cfg["cmd"]
        found = shutil.which(cmd)
        key_set = "✓" if cfg["api_key"] else "✗"
        if found:
            print(f"  {name:12s} {cmd:12s} installed ✓  key {key_set}")
        else:
            print(f"  {name:12s} {cmd:12s} NOT FOUND ✗  key {key_set}")


def main():
    check_harnesses()
    print()

    retry = "--retry-failed" in sys.argv
    drift = "--drift-check" in sys.argv
    list_drift = "--list-drift" in sys.argv
    once = "--once" in sys.argv or retry or drift

    if list_drift:
        drifted = find_drifted_services()
        if not drifted:
            print("[verifier] No drifted services (all latest runs match prior passing state).")
        else:
            print(f"[verifier] {len(drifted)} drifted service(s) — previously passed, now failing:")
            for d in drifted:
                print(f"  - {d['slug']:20s} last failed at {d['latest_failed_at']}")
        return

    if retry:
        print("[verifier] Re-queuing failed services...")
        count = retry_failed_services()
        print(f"[verifier] Re-queued {count} service(s)")

    if drift:
        # Phase 4: re-run verified services whose last check is stale.
        # Intended to be run on a schedule (cron / systemd timer).
        staleness = 24
        for arg in sys.argv:
            if arg.startswith("--staleness-hours="):
                staleness = int(arg.split("=", 1)[1])
        print(f"[verifier] Drift check: queuing re-runs for services stale >{staleness}h...")
        count = queue_drift_check(staleness_hours=staleness,
                                   verifier_version=VERIFIER_VERSION)
        print(f"[verifier] Queued {count} drift-check run(s)")

    if once:
        print("[verifier] Running single poll...")
        count = asyncio.run(poll_once())
        print(f"[verifier] Done. Processed {count} run(s).")
    else:
        asyncio.run(poll_loop())


if __name__ == "__main__":
    main()
